### ISSUE TITLE
SSL certificate is expired

### ISSUE THREAD

**Issue by cdlans** [PintaProject/website#14] opened 2020-04-01 10:11 UTC
Chrome does not load the website.

Expired: Sunday, 29. March 2020 at 00:23:00 Central European Standard Time

**Comment by cameronwhite** [comment] 2020-04-01 23:41
Thanks for the heads up, I've messaged the original maintainer (Jonathan) who's in charge of the website

**Comment by cameronwhite** [comment] 2020-04-01 23:42
I'll close this as a duplicate of https://bugs.launchpad.net/pinta/+bug/1869740

**Closed as completed by cameronwhite** 2020-04-01 23:42 UTC
